### ISSUE TITLE
\xN\  escapes confuse the lexer

### ISSUE THREAD

**Issue by guregu** [jeff-hykin/better-prolog-syntax#2]
Hello, thanks for this extension, I like it a lot.
I found an issue with escapes like this:

```prolog
foo :- write('\x2\').
```

I think maybe it's not looking for the closing backslash? `\xNN\` escapes are a bit weird in that they need a closing one (unlike `\uNNNN` escapes).

![2022-10-07 (1)](https://user-images.githubusercontent.com/131059/194480736-f3f1d8ed-3bfb-4490-88ce-97f8f9482469.png)

**Comment by jeff-hykin** [comment]
Oh it thinks the backslash is escaping the `'` do you have a reference link to how those special escapes work? I've never seen them before. 

This fix shouldn't be too hard to add

**Comment by guregu** [comment]
There's a bit about it here:
https://www.swi-prolog.org/man/syntax.html

> \xXX..\\
> Hexadecimal specification of a character. The closing \ is obligatory according to the ISO standard, but optional in SWI-Prolog [...]

I think it's OK to support only the ISO version.

**Comment by jeff-hykin** [comment]
(Oh no, looks like the syntax also currently doesn't account for nested comments)
That link was really helpful, and I think I fixed (published update just now) it but I've got a few questions you might be able to help with
1. I really do not understand the octal syntax
2. I'm not 100% the `\xX\` is implemented correct, because this sentence from the site doesn't make any sense to me; " code \xa\3 emits the character 10 (hexadecimal‘a') followed by‘3'. " 
3. is `''` an escape? I can't tell if `''''` is just an edgecase or if its using a general escaping technique
4. They say single quote, but use a unicode forward-quote `’`, and then talk about the ASCII single quote `'` so its unclear if only `\'` is an escape or if the unicode `\’` is also an escape
5. Backquote? do they literally mean the unicode `\‘` is an escape? I can't imagine why it is escaped, does prolog allow forward-quote and back-quote as string delimiters?

Eventually I'll install an swipl again and answer these with trial-an-error. But if you know some of the answers it would be helpful.
